#!/usr/bin/env python

import unittest
from tests import all_tests
from os.path import dirname, abspath, join
import os
import sys

if __name__ == "__main__":
    # Include squealy library into python path
    PROJECT_ROOT = dirname(abspath(__file__))
    DJANGO_ROOT = join(PROJECT_ROOT, "example")
    sys.path.insert(0, DJANGO_ROOT)

    tests = all_tests()
    results = unittest.TextTestRunner().run(tests)
