export let CHART_DATA = [
  {
    'id':80,
    'name':'test-chart',
    'url':'test-chart',
    'can_edit': true,
    'query':'select a.name,sum(b.hrs) as \'Spent Hours\' from\n(select * from timesheet_timesheet where day between \n{{params.start_date}} and  {{params.end_date}} ) b join timesheet_timesheettype a\non a.id=b.type_id where b.project_code = {{params.project_code}} group by a.name;',
    'type':'ColumnChart',
    'options':{

    },
    'account':null,
    'transformations':[

    ],
    'validations':[

    ],
    'parameters':[
      {
        'id':57,
        'name':'start_date',
        'data_type':'date',
        'mandatory':false,
        'default_value':'2016-01-01',
        'test_value':'2016-01-01',
        'type':1,
        'kwargs':{

        },
        'chart':80
      },
      {
        'id':58,
        'name':'end_date',
        'data_type':'date',
        'mandatory':false,
        'default_value':'2017-01-01',
        'test_value':'2017-01-01',
        'type':1,
        'kwargs':{

        },
        'chart':80
      },
      {
        'id':59,
        'name':'project_code',
        'data_type':'string',
        'mandatory':false,
        'default_value':'',
        'test_value':'FROL',
        'type':1,
        'kwargs':{

        },
        'chart':80
      }
    ]
  },
  {
    'id':79,
    'user_permission': 'edit',
    'name':'test22',
    'url':'test22',
    'can_edit': true,
    'query':'select a.name,sum(b.hrs) as \'Spent Hours\' from\n(select * from timesheet_timesheet where day between \n{{params.start_date}} and  {{params.end_date}} ) b join timesheet_timesheettype a\non a.id=b.type_id where b.project_code = {{params.project_code}} group by a.name;',
    'type':'LineChart',
    'options':{

    },
    'account':null,
    'transformations':[

    ],
    'validations':[

    ],
    'parameters':[
      {
        'id':54,
        'name':'start_date',
        'data_type':'date',
        'mandatory':false,
        'default_value':'2016-01-01',
        'test_value':'2016-01-01',
        'type':1,
        'kwargs':{

        },
        'chart':79
      },
      {
        'id':55,
        'name':'end_date',
        'data_type':'date',
        'mandatory':false,
        'default_value':'2017-01-01',
        'test_value':'2017-01-01',
        'type':1,
        'kwargs':{

        },
        'chart':79
      },
      {
        'id':56,
        'name':'project_code',
        'data_type':'string',
        'mandatory':false,
        'default_value':'FROL',
        'test_value':'HASHEDIN',
        'type':1,
        'kwargs':{

        },
        'chart':79
      }
    ]
  },
  {
    'id':78,
    'name':'test1ghs',
    'url':'test1ghs',
    'can_edit': true,
    'query':'select a.name,sum(b.hrs) as \'Spent Hours\' from\n(select * from timesheet_timesheet where day between \n{{params.start_date}} and  {{params.end_date}} ) b join timesheet_timesheettype a\non a.id=b.type_id where b.project_code = {{params.project_code}} group by a.name;',
    'type':'AreaChart',
    'options':{
      'chartArea':{
        'width':'100%',
        'top':'10%',
        'height':'50%',
        'left':'10%'
      },
      'hAxis':{
        'gridlines':{
          'color':'#ccc',
          'count':4
        },
        'viewWindow':{
          'max':5,
          'min':0
        },
        'scaleType':'log',
        'titleTextStyle':{
          'color':'#000',
          'fontSize':17
        },
        'title':'X-Axis Data'
      },
      'title':'Chart Title',
      'tooltip':{
        'isHtml':true,
        'showColorCode':true,
        'textStyle':{
          'color':'#FF0000'
        }
      },
      'height':240,
      'width':400,
      'colors':[
        '#e0440e',
        '#e6693e',
        '#ec8f6e',
        '#f3b49f',
        '#f6c7b6'
      ],
      'animation':{
        'duration':1000,
        'easing':'out',
        'startup':true
      },
      'annotations':{
        'textStyle':{
          'opacity':0.8,
          'fontName':'Times-Roman',
          'bold':true,
          'color':'#871b47',
          'auraColor':'#d799ae',
          'fontSize':18,
          'italic':true
        },
        'highContrast':true,
        'boxStyle':{
          'stroke':'#888',
          'rx':10,
          'ry':10
        },
        'backgroundColor':'#ff0000'
      },
      'vAxis':{
        'gridlines':{
          'color':'#ccc',
          'count':4
        },
        'minValue':5,
        'titleTextStyle':{
          'color':'#000'
        },
        'maxValue':100,
        'title':'Y-Axis Data'
      },
      'legend':{
        'position':'top',
        'textStyle':{
          'color':'#0000ff',
          'fontSize':16
        }
      }
    },
    'account':null,
    'transformations':[

    ],
    'validations':[

    ],
    'parameters':[
      {
        'id':51,
        'name':'start_date',
        'data_type':'string',
        'mandatory':false,
        'default_value':'2016-01-01',
        'test_value':'2016-01-01',
        'type':1,
        'kwargs':{

        },
        'chart':78
      },
      {
        'id':52,
        'name':'end_date',
        'data_type':'string',
        'mandatory':false,
        'default_value':'2017-01-01',
        'test_value':'2017-01-01',
        'type':1,
        'kwargs':{

        },
        'chart':78
      },
      {
        'id':53,
        'name':'project_code',
        'data_type':'string',
        'mandatory':false,
        'default_value':'FROL',
        'test_value':'FROL',
        'type':1,
        'kwargs':{

        },
        'chart':78
      }
    ]
  }
]


export let CHART_RESPONSE = {
  'rows': [
    {
      'c':[
        {
          'v':'Client Meet'
        },
        {
          'v':6.333333333333333
        }
      ]
    },
    {
      'c':[
        {
          'v':'Consulting'
        },
        {
          'v':2.5
        }
      ]
    },
    {
      'c':[
        {
          'v':'Debug'
        },
        {
          'v':4.833333333333333
        }
      ]
    },
    {
      'c':[
        {
          'v':'Design'
        },
        {
          'v':107.0
        }
      ]
    },
    {
      'c':[
        {
          'v':'Dev'
        },
        {
          'v':48.0
        }
      ]
    },
    {
      'c':[
        {
          'v':'Documentation'
        },
        {
          'v':4.333333333333333
        }
      ]
    },
    {
      'c':[
        {
          'v':'Email'
        },
        {
          'v':10.083333333333332
        }
      ]
    },
    {
      'c':[
        {
          'v':'Finance'
        },
        {
          'v':6.583333333333337
        }
      ]
    },
    {
      'c':[
        {
          'v':'Help'
        },
        {
          'v':7.0
        }
      ]
    },
    {
      'c':[
        {
          'v':'Internal'
        },
        {
          'v':27.416666666666668
        }
      ]
    },
    {
      'c':[
        {
          'v':'Interview'
        },
        {
          'v':9.83333333333334
        }
      ]
    },
    {
      'c':[
        {
          'v':'Learning'
        },
        {
          'v':81.5
        }
      ]
    },
    {
      'c':[
        {
          'v':'Meeting'
        },
        {
          'v':170.15
        }
      ]
    },
    {
      'c':[
        {
          'v':'Onboarding'
        },
        {
          'v':9.0
        }
      ]
    },
    {
      'c':[
        {
          'v':'Other'
        },
        {
          'v':231.9666666666667
        }
      ]
    },
    {
      'c':[
        {
          'v':'Planning'
        },
        {
          'v':6.166666666666666
        }
      ]
    },
    {
      'c':[
        {
          'v':'PMO'
        },
        {
          'v':4.25
        }
      ]
    },
    {
      'c':[
        {
          'v':'Pre-sales'
        },
        {
          'v':1.083333333333333
        }
      ]
    },
    {
      'c':[
        {
          'v':'Proposals'
        },
        {
          'v':3.0
        }
      ]
    },
    {
      'c':[
        {
          'v':'Review'
        },
        {
          'v':13.333333333333325
        }
      ]
    },
    {
      'c':[
        {
          'v':'Training'
        },
        {
          'v':28.166666666666668
        }
      ]
    }
  ],
  'cols':[
    {
      'type':'string',
      'id':'name',
      'label':'name'
    },
    {
      'type':'number',
      'id':'Spent Hours',
      'label':'Spent Hours'
    }
  ]
}