# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-29 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squealy', 'default_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, unique=True)),
                ('query', models.TextField()),
                ('name', models.CharField(max_length=255)),
                ('database', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
