# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-29 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squealy', '0001_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
