# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squealy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='validation',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chart',
            name='format',
            field=models.CharField(default='GoogleChartsFormatter', max_length=50),
        ),
    ]
