# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-15 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squealy', '0001_chart_database'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='database',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
