# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squealy', '0002_auto_20170223_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='format',
            field=models.CharField(default='', max_length=50),
        ),
    ]
