# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-30 13:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squealy', '0001_scheduledreport_template'),
        ('squealy', '0002_parameter_order'),
    ]

    operations = [
    ]
