# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-24 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squealy', '0002_auto_20170315_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='chart',
            name='url',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
