# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-22 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('squealy', '0002_auto_20170315_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=300)),
                ('parameter_value', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ReportRecipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('last_run_at', models.DateTimeField()),
                ('next_run_at', models.DateTimeField()),
                ('cron_expression', models.CharField(max_length=200)),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_report', to='squealy.Chart')),
            ],
        ),
        migrations.AddField(
            model_name='reportrecipient',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportrecep', to='squealy.ScheduledReport'),
        ),
        migrations.AddField(
            model_name='reportparameter',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportparam', to='squealy.ScheduledReport'),
        ),
    ]
