# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 20:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squealy', '0003_parameter_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameter',
            name='format',
        ),
    ]
