# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-22 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squealy', '0003_auto_20170322_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledreport',
            name='last_run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheduledreport',
            name='next_run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
