# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-24 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squealy', '0004_auto_20170324_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
