# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 20:05
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squealy', '0004_remove_parameter_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='kwargs',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
