# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-27 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squealy', '0004_auto_20170322_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='chart',
            name='url',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
