# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-29 04:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('squealy', '0005_auto_20170327_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledReportChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='squealy.Chart')),
            ],
        ),
        migrations.RemoveField(
            model_name='scheduledreport',
            name='chart',
        ),
        migrations.AddField(
            model_name='scheduledreportchart',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='squealy.ScheduledReport'),
        ),
    ]
