# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-03 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squealy', '0005_parameter_dropdown_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='is_parameterized',
            field=models.BooleanField(default=False),
        ),
    ]
