# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squealy', '0005_parameter_kwargs'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='test_value',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
