# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-06 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squealy', '0005_parameter_dropdown_api'),
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('dj_url', models.CharField(max_length=500)),
            ],
        ),
    ]
