# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-03 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('squealy', '0006_parameter_is_parameterized'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('default_value', models.CharField(blank=True, max_length=200, null=True)),
                ('test_value', models.CharField(blank=True, max_length=200, null=True)),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='squealy.Filter')),
            ],
        ),
    ]
