# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-06 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squealy', '0006_database'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='display_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
