# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-10 07:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squealy', '0007_auto_20170406_0945'),
        ('squealy', '0008_chart_transpose'),
    ]

    operations = [
    ]
