# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-14 09:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squealy', '0009_merge_20170410_0755'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Database',
        ),
    ]
