# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-01 06:42
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.hashers import make_password


def create_default_superuser(apps, schema_editor):
    """
    Creates a default super user
    """
    User = apps.get_model('auth', 'user')
    default_super_user = User(
        username="admin",
        is_superuser=True,
        password=make_password("admin@123"),
        is_staff=True
    )
    default_super_user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('squealy', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_superuser),
    ]
