# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-16 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketDynamic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('format', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('value', models.FloatField()),
                ('volume', models.FloatField()),
                ('total_value', models.FloatField()),
                ('total_volume', models.FloatField()),
            ],
        ),
    ]
