# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-16 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blueocean', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionKPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('quarter', models.CharField(max_length=100)),
                ('aware', models.FloatField()),
                ('not_aware', models.FloatField()),
                ('criteria', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='MarketKPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('quarter', models.CharField(max_length=100)),
                ('kpi', models.FloatField()),
            ],
        ),
    ]
