# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-16 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blueocean', '0002_executionkpi_marketkpi'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharePerBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('value2014', models.FloatField()),
                ('value2015', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SharePerCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('value2014', models.FloatField()),
                ('value2015', models.FloatField()),
            ],
        ),
    ]
